# Generated by Django 3.2.13 on 2022-07-01 12:57

from django.db import migrations, models
import render_static.tests.enum.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnumTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_pos_int', render_static.fields.EnumPositiveSmallIntegerField(choices=[(1, 'Value 1'), (2, 'Value 1'), (3, 'Value 1')], default=None, enum=render_static.tests.enum.models.SmallPosIntEnum, null=True)),
                ('small_int', render_static.fields.EnumSmallIntegerField(choices=[(-1, 'Value -1'), (0, 'Value 0'), (1, 'Value 1'), (2, 'Value 1'), (3, 'Value 1')], default=3, enum=render_static.tests.enum.models.SmallIntEnum)),
            ],
        ),
    ]
